export const drawerConstants = {
    CHANGE_DRAWER_TO_TRUE: "CHANGE_DRAWER_TO_TRUE",
    CHARGE_DRAWER_TO_FALSE: "CHARGE_DRAWER_TO_FALSE"
}

export const categoryConstants = {
    GET_ALL_CATEGORIES_REQUEST: 'GET_ALL_CATEGORIES_REQUEST',
    GET_ALL_CATEGORIES_SUCCESS: 'GET_ALL_CATEGORIES_SUCCESS',
    GET_ALL_CATEGORIES_FAILURE: 'GET_ALL_CATEGORIES_FAILURE',
    ADD_NEW_CATEGORY_REQUEST: 'ADD_NEW_CATEGORY_REQUEST',
    ADD_NEW_CATEGORY_SUCCESS: 'ADD_NEW_CATEGORY_SUCCESS',
    ADD_NEW_CATEGORY_FAILURE: 'ADD_NEW_CATEGORY_FAILURE'
}

export const serviceConstants = {
    GET_ALL_SERVICES_SUCCESS: 'GET_ALL_SERVICES_SUCCESS',
    GET_ALL_SERVICES_FAILURE: 'GET_ALL_CATEGORIES_FAILURE'
}

export const bookingConstants = {
    GET_ALL_BOOKING_SUCCESS: 'GET_ALL_BOOKING_SUCCESS',
    GET_ALL_BOOKING_FAILURE: 'GET_ALL_BOOKING_FAILURE'
}
